
# Provider for Kid and User
login_check:
  path: /api/v1/login/user/login_check
kid_login_check:
  path: /api/v1/login/kid/login_check

# API chek token with JWT
api_login_check:
    path: /api/login_check
