
#index:
#    path: /
#    controller: App\Controller\DefaultController::index
login_check:
  path: /api/v1/login/user/login_check
kid_login_check:
  path: /api/v1/login/kid/login_check




#index:
#    path: /
#    controller: App\Controller\DefaultController::index
# login_check:
#   path: /login_check
# admin_login_check:
#   path: /admin/login_check