### List all users
GET http://localhost:8000/api/v1/users

###List user by id
GET http://localhost:8000/api/v1/users/121

### List all book
GET http://localhost:8000/api/v1/books


### List all the books of one child by id
GET http://localhost:8000/api/v1/kids/176/books

### list all the books a kid wishes to read
GET http://localhost:8000/api/v1/kids/176/books/wish

### list all the authors for one kid
GET http://localhost:8000/api/v1/kids/194/books/authors

###list all books of author for one kid

GET  http://localhost:8000/api/v1/kids/121/books/authors/91

###create kid for user
POST http://localhost:8000/api/v1/users/121/kids

###update user by id
PATCH http://localhost:8000/api/v1/users/121

